### ISSUE TITLE
ImportError: No module named android when trying to run lbryum on Android 

### ISSUE THREAD

**Issue by aayanl** [lbryio/lbryum#126]
Android 6.0.1, Terminal Emulator: Termux

It's fine if this is a wontfix, just curious if this would work

`python2 lbryum`
```
Traceback (most recent call last):
  File "lbryum", line 337, in <module>
    gui = init_gui(config, network, daemon, plugins)
  File "lbryum", line 95, in init_gui
    gui = __import__('lbryum_gui.' + gui_name, fromlist=['lbryum_gui'])
  File "/data/data/com.termux/files/home/lbryum/gui/android.py", line 23, in <module>
    import android
ImportError: No module named android
[Plugins] stopped
```

**Comment by jackrobison** [comment]
It looks like you're running a pre-3.x.x version. You might have better luck with what's current, although maybe not. The GUI, plugins, and the code that's supposed to make android work (but didn't, as far as I know) has been removed.

It'd be awesome for lbryum to work on android. Give the current version a shot and let us know what issues you inevitably run into!
