### ISSUE TITLE
Winning claims with supports fail to resolve due to amount formatting error

### ISSUE THREAD

**Issue by jackrobison** [lbryio/lbryum#142]

**Comment by tzarebczan** [comment]
Does this fix all the issues described here? https://github.com/lbryio/lbry/issues/804

**Comment by kaykurokawa** [comment]
I believe it should fix that although you may need to clear out your cache for the changes to take place

**Comment by kauffj** [comment]
Closing as this appears to be fixed, @jackrobison re-open if I'm misunderstanding.
