### ISSUE TITLE
prevout_hash and prevout_n are terrible names. use txid and nout instead

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbryum#166]
for example, in the `listunspent` command.

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by kauffj** [comment]
Possibly related: should outpoint just be returned as a first class field in some or many cases?

I understand that it is just a concatenation of a txid and nout with a colon between them, but I've already seen this (admittedly simple) code repeated in the app several times over, and I wonder if it makes sense to just explicitly return it.
