### ISSUE TITLE
getnameclaims raises Exception if there are claim values that are not lbryschema decodeable

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbryum#171]
If I make a getnameclaims call with a claim that is not lbryschema decodeable, I get this error when calling getnameclaims: 

File \"/app/lib/python2.7/site-packages/lbryum/commands.py\", line 1581, in getnameclaims | KeyError: 'a7501ac45889528af61a8662fd0f7ca6579c2c41'", "code": -32603}

https://github.com/lbryio/lbryum/blob/master/lbryum/commands.py#L1581

This breaks lbryum_testing.py in lbry-in-a-box

**Comment by tzarebczan** [comment]
Is this different from the keyerror that was just recently fixed? https://github.com/lbryio/lbryum/issues/168

**Comment by kaykurokawa** [comment]
No its a different issue
