### ISSUE TITLE
Redownload blockchain_headers if blocks to sync are large

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbryum#175]
For user that hasn't run LBRY in a while, the first app start experience is slow because it needs to catch up with the blockchain which can take a while if there are tons of blocks. Would it be possible to download the blockchain_headers instead and sync from there?

**Comment by lyoshenka** [comment]
I'm putting this on the wishlist because its such a quick win and its SO annoying when you're 200K blocks behind

**Comment by kauffj** [comment]
1) Is this a forever requirement? My blockchain headers are ~35MB right now. In 3 years, will all app users on all systems need 100MB of headers?
2) If 35MB of headers are necessary for everyone to use the app, maybe we should look at shipping snapshots of the blockchain headers in the builds themselves. An extra 35MB at download time feels better than another download after you launch the app. I bet @IGassmann could tackle this.

**Comment by hackrush01** [comment]
This will now be done on the daemon side.
