### ISSUE TITLE
Track content purchases and incoming payments in transaction

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbryum#176]
In order to support https://github.com/lbryio/lbry/issues/803, the wallet needs to be able to tie back incoming transactions to claims if they are for incoming content payments as well as outgoing transactions for content purchases. 

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by eukreign** [comment]
We have a set of internal proposals for this and are tracking it elsewhere.
