### ISSUE TITLE
Get information about abandoned claims preferably by using `claim_id`

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbryum#180]
## Edit By @hackrush01(on 17th Dec, 17)
We need a way to get the claim information about previously abandoned claims(it would be good if we can get that by `claim_id` or `<name>#<claim_id>` using the `getclaimsbyids` or similar function). Lack of this leads to gaps in txn list when called using `lbryum claimhistory` and `lbryum tiphistory` due to the way it is currently implemented, also the other reason is explained below by @tzarebczan.

### Tip designation disappears after claim is abandoned (shows as spend) / updated (shows as support)
If I receive a tip on a claim, the Transaction history marks it as an incoming tip along with the claim name. The sending also sees the tip transaction, claim name and amount. 

If the claim is abandoned, the tip designation disappears from the tx list and just shows as "received". On the sender side, it just shows as "sent".  This means the tip can't be abandoned via the tx list anymore and there's no indication that this was originally a tip.

If the claim is updated, the tip designation changes to a "supports" on both the sender and receiver side. This makes it a bit confusing because if you try to delete the supports, it thinks you are deleting a claim - "Confirm Claim Revoke Are you sure want to revoke this claim?

This may be related to https://github.com/lbryio/lbry/issues/941, but even if the tip is abandoned/updated along with the claim, it should continue to be designated as a tip.

**Comment by hackrush01** [comment]
A patch has been made for this, to display the correct information.
Information about abandoned claims is not directly retrievable.
Closing
