### ISSUE TITLE
Latest RC: Failed to process channel_new: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbryum#182]
On the latest RC, get an error when trying to create a channel. The certificate is written and channel is created, but it allows you to create the same channel multiple times.

https://pastebin.com/zGcY99ys

**Comment by jackrobison** [comment]
fixed in https://github.com/lbryio/lbry/pull/1023

**Comment by kaykurokawa** [comment]
I don't understand how lbryio/lbry#1023 fixes this issue. And I'm not certain exactly what tom means when he says "allows you to create the same channel multiple times". Do you mean that the channel was updated? because that's what's supposed to happen. 

Also , In the logs, it says that the channel_new command failed.

**Comment by tzarebczan** [comment]
@kaykurokawa - I believe the user was able to run the claim_new command twice for the same name 
 because of this bug. Besides the error, the claims were created, the private keys were written to the wallet file and showed in his claims. 

https://explorer.lbry.io/tx/efbbe89330324774bd186c996dc93cf2d7eab6e1c471eea02754d140df4a315f?address=bXB2QALfpBD7UDBijJ21n9RF1EYNGaJHQ5#bXB2QALfpBD7UDBijJ21n9RF1EYNGaJHQ5

https://explorer.lbry.io/tx/b9affb7d7c94a376b89607205b0a346009eb7fd9fe67f37ba5a23cb598c7e7a9?address=badHNnqq9bBdTdLH8yxRkeP91wq7GCikhE#badHNnqq9bBdTdLH8yxRkeP91wq7GCikhE

from our chat:

"claimtrie_transactions": {
        "b9affb7d7c94a376b89607205b0a346009eb7fd9fe67f37ba5a23cb598c7e7a9:0": 9,
        "efbbe89330324774bd186c996dc93cf2d7eab6e1c471eea02754d140df4a315f:0": 9
},

He then tried it on v18:
]ProfessorDey: claim_list @ProfessorDey does give both claims though
[2:17 PM] ProfessorDey: claim sequences 1 and 2
[2:19 PM] ProfessorDey: Trying channel_new @ProfessorDey 10 results in an error of Don't know which claim to update

so he ended up abandoning the first.

**Comment by jackrobison** [comment]
fixed for real in https://github.com/lbryio/lbryum/pull/185
