### ISSUE TITLE
Outputs with same address and type should be grouped together.

### ISSUE THREAD

**Issue by hackrush01** [lbryio/lbryum#205]
Happen when specifying `change_addr=return_addr` while calling `make_unsigned_transaction()`.
Ex.
```json
[
  [
    1, 
    "bLK6HuxfWZDsC2831WLo3xFzYw3BRZ9RaL", 
    10000
  ], 
  [
    1, 
    "bLK6HuxfWZDsC2831WLo3xFzYw3BRZ9RaL", 
    572200
  ]
]
```

**Comment by tzarebczan** [comment]
@eukreign will this be covered by the new wallet work?

**Comment by eukreign** [comment]
I would say this is WontFix because it's perfectly reasonable to split some UTXO into several new UTXOS even if they go into the same address. The funding command does something like this intentionally.
