### ISSUE TITLE
List all lbryum commands that we use

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbryum#206]
abandon
broadcast
cansignwithcertificate
check_seed
claim
claimcertificate
claimhistory
commands
create
~createmultisig~
createrawtx
decrypt
deseed
deserialize
dumpprivkeys
encrypt
exportcertificateinfo
~freeze~
getaddressbalance
getaddresshistory
getaddressunspent
~getalias~
getbalance
getbestblockhash
getblock
getcertificateclaims
getcertificatesforsigning
getclaimbyid
getclaimbynameinchannel
getclaimbyoutpoint
getclaimsbyids
getclaimsforname
getclaimsfromtx
getclaimsinchannel
getclaimssignedby
~getclaimtrie~
getconfig
getdefaultcertificate
getleastusedaddress
getleastusedchangeaddress
getmasterprivate
getmerkle
getmostrecentblocktime
~getmpk~
getnameclaims
getnetworkstatus
getnthclaimforname
~getprivatekeys~
getproof
getpubkeys
getseed
getservers
getsignaturebyid
gettransaction
getunusedaddress
getutxoaddress
getvalueforname
getvalueforuri
getvaluesforuris
history
importcertificateinfo
importprivkey
ismine
listaddresses
~listcontacts~
listunspent
make_seed
notify
password
payto
renewclaim
renewclaimsbeforeexpiration
requestvalueforname
restore
~searchcontacts~
sendclaimtoaddress
sendwithsupport
setconfig
~setlabel~
signmessage
signtransaction
support
sweep
transactionfee
~unfreeze~
update
updatecertificate
updateclaimsignature
updatesupport
validateaddress
~verify_claim_schema~
verifymessage
**version**
waitfortxinwallet

**Comment by jackrobison** [comment]
Here are all of the lbryum commands currently:

```
restore
getclaimbyid
getconfig
gettransaction
getseed
requestvalueforname
version
getleastusedaddress
getclaimsforname
exportcertificateinfo
updateclaimsignature
getunusedaddress
transactionfee
password
getclaimsinchannel
getutxoaddress
deserialize
getsignaturebyid
check_seed
getbestblockhash
getnthclaimforname
freeze
getaddresshistory
createrawtx
getmostrecentblocktime
getclaimtrie
getnetworkstatus
getproof
sendwithsupport
getclaimsfromtx
setconfig
verify_claim_schema
ismine
getbalance
setlabel
getaddressbalance
getmpk
getclaimssignedby
commands
listunspent
listcontacts
support
dumpprivkeys
getcertificatesforsigning
sweep
getvalueforuri
notify
getcertificateclaims
updatecertificate
cansignwithcertificate
claimcertificate
create
importprivkey
validateaddress
getclaimsbyids
getvalueforname
importcertificateinfo
broadcast
renewclaimsbeforeexpiration
getdefaultcertificate
getvaluesforuris
signmessage
deseed
abandon
history
claim
getnameclaims
signtransaction
getmerkle
decrypt
getpubkeys
verifymessage
make_seed
getprivatekeys
encrypt
sendclaimtoaddress
waitfortxinwallet
payto
createmultisig
claimhistory
getleastusedchangeaddress
update
renewclaim
getclaimbyoutpoint
getaddressunspent
getclaimbynameinchannel
updatesupport
getservers
listaddresses
searchcontacts
getalias
unfreeze
getmasterprivate
getblock```

**Comment by lyoshenka** [comment]
please bold the ones you do use. that way if any are left unbolded and uncrossed, we can discuss them

**Comment by lyoshenka** [comment]
@jackrobison im moving your list into the top so we can all edit it

**Comment by eukreign** [comment]
@lyoshenka @jackrobison @hackrush01 Looks like only **version** is bold so far, should be easy to write tests! :-D

**Comment by kaykurokawa** [comment]
Here are all the commands used in lbrynet daemon, so they should be prioritized. 

getbalance                        
payto                             
getblock                          
gettransaction
getnameclaims                     
getclaimsforname                  
claim                             
abandon                           
support                           
sendwithsupport                   
payto                             
getvalueforname                   
getvalueforuri                    
getvaluesforuris                  
claimcertificate                  
getcertificateclaims              
getclaimsfromtx                   
getclaimbyoutpoint                
getclaimbyid                      
getclaimtrie                      
claimhistory                      
ismine                            
getpubkeys                        
listaddresses                     
listunspent                       
sendclaimtoaddress                
importcertificateinfo             
exportcertificateinfo            
getcertificatesforsigning        
renewclaimsbeforeexpiration      
renewclaim

**Comment by lyoshenka** [comment]
id say some of the crossed-out commands are safe to remove (like setlabel) and some we should keep (like createmultisig)

**Comment by eukreign** [comment]
Going to close this issue for iteration planning purposes but if anyone has any further updates please don't hesitate to update this issue and I'll take your feedback into account.
