### ISSUE TITLE
lbryum default wallet directory different from app/daemon

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbryum#217]
@eukreign ran into this issue recently. If you run lbryum as a standalone wallet, it defaults to ~/.lbryum as the wallet directory. This is especially confusing for users that may have LBRY/lbry-daemon installed since it will create a new wallet in ~/.lbryum and won't show the app balance/transactions. The app/daemon creates the wallet in ~/.local/share/lbry/lbryum

This is even more confusing because if you start LBRY after installing/running lbryum standalone, LBRY will now find the ~/.lbryum directory and use it as a wallet, and at the same time, create a new ~/.lbrynet directory (and no longer look at ~/.local/share/lbry/lbrynet)

**Comment by kaykurokawa** [comment]
It is possible to change wallet path and lbryum with the "-w" and "-D" option when running lbryum through the command line. 

It would be nice though if the default behavior in lbryum was the same as lbrynet daemon as dertermined by https://github.com/lbryio/lbry/blob/master/lbrynet/conf.py

**Comment by tzarebczan** [comment]
Since the new wallet is integrated into the daemon, there's no way to run as a standalone. If there ever is, it should use the same defaults as lbrynet.
