### ISSUE TITLE
Lbryum private key header is wrong

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbryum#218]
As reported by @tzarebczan :

Lbryum uses a different private key header (0x80 /128 in decimal, this is the standard in Bitcoin) than what is used in Lbrycrd (0x1c / 28) : 
https://github.com/lbryio/lbrycrd/blob/master/src/chainparams.cpp#L178

See: 
https://github.com/lbryio/lbryum/blob/master/lbryum/lbrycrd.py#L186
https://github.com/lbryio/lbryum/blob/master/lbryum/lbrycrd.py#L193

This will cause problem when importing private keys from lbrycrd to lbryum and vice versa.

Lbryum should use the same format as that used in lbrycrd (0x1c). But we also need to make sure that it accepts header 0x80 since people may have old lbryum wallets that they will want to import into new lbryum wallets with updated private key header.

**Comment by tzarebczan** [comment]
This is now correct in the new wallet.
