### ISSUE TITLE
Install process lacks daemonization instructions

### ISSUE THREAD

**Issue by lbrydocs** [lbryio/lbryum#220]
I am testing various LBRY component install processes ahead of writing new README/INSTALL files. I use Lubuntu 16.04.3 LTS for this, which is a clone of Ubuntu, but stripped of its heavy graphical environment, so VMs use about half the disk space.

The lbryum install process yields a script in /usr/local/bin/, but there are no instructions on how to turn it into a daemon that auto-starts. Based on my observation we're supposed to be doing this as systemd services. The example config file from Electrum is also suspect - this looks like it might try to attach to something in the Bitcoin universe, rather than LBRY.

I am available as D. Ray Blanco on Discord if the developer who fixes this has any questions or needs me to test once fixes are in place.

> Configuration file for the electrum client
> Settings defined here are shared across wallets
> 
>  copy this file to /etc/electrum.conf if you want read-only settings
>  copy it into your ~/.electrum/ directory if you want global settings
>  that can be rewritten by the client
> 
> [client]
> server = electrum.novit.ro:50001:t
> proxy = None
> gap_limit = 5
>  booleans use python syntax
> use_change = True
> num_zeros = 2
>  default transaction fee is in Satoshis
> fee = 10000
> winpos-qt = [799, 226, 877, 435]

**Comment by eukreign** [comment]
this no longer makes sense, wallet is built-in to the daemon now
