### ISSUE TITLE
Use different algo for Choosing Coins

### ISSUE THREAD

**Issue by hackrush01** [lbryio/lbryum#221]
Based on [this](https://github.com/lbryio/lbryum/pull/213#issuecomment-363139432) comment:

If our actual goal is to prioritize small unspents, which would be a good thing for our application (some of our apps create a lot of small transactions resulting in a lot of small unspents), we could create a new CoinChooser which does that and just ignores coin age (how old the unspent is), and use it instead.

Transaction priority is not really a thing anymore since Bitcoin Core version 0.12 ( lbrycrdd is > 0.12 ) (see bitcoin/bitcoin#7022 for more information ) so giving priority to coin age (returning the oldest coin) doesn't make sense anymore. Current upstream electrum version completely removed CoinchooserOldestFirst and uses the privacy chooser.

**Comment by hackrush01** [comment]
@lyoshenka Can a `level: 3` issue also be a good first issue?

**Comment by lyoshenka** [comment]
@eukreign did this in txlbryum, so I'm closing this.
