### ISSUE TITLE
Trimming commands.py and wallet.py, etc.

### ISSUE THREAD

**Issue by eukreign** [lbryio/lbryum#223]
This is the opposite of https://github.com/lbryio/lbryum/issues/206

Please think of commands in `lbryum/commands.py` that do not make sense and should be removed (or makes sense but still should be removed) please add them in comments below.

`lbryum/wallet.py` also has many wallet implementations, if we can remove any of the implementations please comment.

`lbryum/coinchooser.py` has 4 coin choosers, do we use/need all 4 of them?

Anything else you can think of that can be removed.

**Comment by eukreign** [comment]
This pull request in lbryum deletes a bunch of stuff (moves it to lbryschema?), we should finish and merge it: https://github.com/lbryio/lbryum/pull/177

**Comment by eukreign** [comment]
Here is the code coverage report for `lbryum/commands.py` you can see which commands aren't tested and perhaps can be removed. If a command is not tested but should be, please not that here as well.

**Comment by lyoshenka** [comment]
this may be a good item for lex-jack-IRL

**Comment by eukreign** [comment]
Further discussion on this can go into #226
