### ISSUE TITLE
Add fees to claim trie transactions

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbryum#232]
Fees should be added to claim trie transactions, the same way it is done in this lbrycrd PR: https://github.com/lbryio/lbrycrd/pull/95

**Comment by tzarebczan** [comment]
@kaykurokawa we can close this right?

**Comment by alyssaoc** [comment]
@kaykurokawa  Can we close this?

**Comment by alyssaoc** [comment]
Issue moved to [lbryio/lbry #1442](https://github.com/lbryio/lbry/issues/1442) via [**ZenHub**](https://www.zenhub.com/)
