### ISSUE TITLE
claim command does not update an existing claim properly

### ISSUE THREAD

**Issue by jackrobison** [lbryio/lbryum#233]
@tzarebczan published claim `1c62e6f3b203667222cb28d3ae194b4572d7eeb4` at block 329135 and then tried to update it at block 329137. Instead of updating, he wound up making a second claim for the same name `v19edittest1` - `a308f2f36684e97ede62beeb856908e282277d16`.

**Comment by tzarebczan** [comment]
This occurred when updating the claim while it was still confirming.  This shouldn't happen via the LBRY-app as we don't show an edit button until the claim is available in Claim_list_mine but could happen if someone is using the API directly.

**Comment by alyssaoc** [comment]
@tzarebczan Have recent changes to claim_list_mine solved this?

**Comment by tzarebczan** [comment]
No longer an issue - was able to update a claim in the same block: 
https://explorer.lbry.io/tx/63df7c4a754638ea520c7f17f0f69b7c9b5a1154d1cd1dcef26a1e380d09f2b7#output-0
https://explorer.lbry.io/tx/f4c3332530af5ab083dcb595d0ae016f7fdfeadbf9b698889fee0a928eb28862#input-8210945
