### ISSUE TITLE
blockchain headers fail to download

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbryum#235]
I downloaded LBRY on my sister's MAC and it failed to download blockchain headers. When this happens, the wallet needs to sync from scratch which takes a long time. 
 The only other time this happened to me was on MAC vm, so I'm not sure if its specific to Mac or maybe some connection issues (but why can it download the blocks manually, but not the headers from S3?)

https://github.com/lbryio/lbryum/blob/d2a4f7492fc3413291b67e4d1cdec2dfcf058355/lbryum/blockchain.py#L156

Update: Had this happen on a Windows PC today at my other sister's house. The experience of having to sync from scratch is painful.

**Comment by nikooo777** [comment]
I suggest retrying at least once. 
Also Today I enabled cloudfront for the the bucket used for the headers. 
I'd suggest setting `http://lbry-blockchain-headers.s3-accelerate.amazonaws.com/blockchain_headers_latest` instead of `https://s3.amazonaws.com/lbry-blockchain-headers/blockchain_headers_latest`, falling back to this one if it fails and retrying both before giving up.

**Comment by tzarebczan** [comment]
Jack's recent changes to the re-download of headers should fix this issue. It did on my Mac at least. It makes the connection to the server in a slightly different way.

**Comment by lyoshenka** [comment]
@nikooo777 it looks like you turned on transfer acceleration, not cloudfront. how does that help us here? It looks like it only speeds up uploads. It doesn't affect download speed or reliability, which is what we actually want.

From https://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html:

> Why Use Amazon S3 Transfer Acceleration?
> You might want to use Transfer Acceleration on a bucket for various reasons, including the following:
> - You have customers that upload to a centralized bucket from all over the world.
> - You transfer gigabytes to terabytes of data on a regular basis across continents.
> - You underutilize the available bandwidth over the Internet when uploading to Amazon S3.

For the record, I don't think cloudfront itself helps us much too. It's only intended for static assets, whereas our headers change every block.

**Comment by nikooo777** [comment]
I indeed got confused there. What I meant to do was use ClourFront.

Here is why: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/MigrateS3ToCloudFront.html
```
Using CloudFront can be more cost effective if your users access your objects frequently because, at higher usage, 
the price for CloudFront data transfer is lower than the price for Amazon S3 data transfer. 
In addition, downloads are faster with CloudFront than with Amazon S3 alone because your objects are stored closer to your users.
```

Perhaps it's worth trying?

**Comment by tzarebczan** [comment]
Yep, let's close it!
