### ISSUE TITLE
Lbryum difficulty retarget algorithm seems to be wrong 

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbryum#238]
Lbryum difficulty retarget algorithm is wrong and should be fixed: https://github.com/lbryio/lbryum/blob/master/lbryum/blockchain.py#L22

**Comment by alyssaoc** [comment]
@kaykurokawa  please confirm if this is still valid or close

**Comment by kaykurokawa** [comment]
Fix looks good in torba, closing
