### ISSUE TITLE
Test proofs without claim information

### ISSUE THREAD

**Issue by shyba** [lbryio/lbryum#240]
There is a bug when a block hash is given to an electrum command and the winner claim in it was abandoned on the following blocks. Currently lbryum server raises an error when resolving a URI like that, but as this gets fixed a proof will come without claim_id or sequence, so lbryum should expect that and not raise an error. Maybe it already does, but we should add a test case in here for it before lbryumx is released (there is no issue for the server side as this is a lbryumx only change).

**Comment by alyssaoc** [comment]
@shyba is this still relevant or can it be closed?

**Comment by shyba** [comment]
It is, but I believe we should fix it on the new wallet instead. However it's a very low priority as it's not a common case and it fixes itself after a while.
