### ISSUE TITLE
getvalueforname returns wrong height

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbryum#26]
lbryum command getvalueforname uses locktime + 1 to get the height which is not necessarily the actual height. 

https://github.com/lbryio/lbryum/blob/master/lib/commands.py#L684

It is actually not clear what height should be though , should it be the "height that the tx was accepted" or "height that the claim  was accepted (AKA takeover height)" (claims can be accepted X blocks after when the tx was accepted due to calimtrie delay). Which is the more useful information? Or should we return both in different variables.

**Comment by kaykurokawa** [comment]
In discussion with Jimmy, we concluded that "height" should be the take over height , and should be returned as "last takeover height". We need to change lbrycrd and lbrynet to account for this.

**Comment by eukreign** [comment]
@kaykurokawa does anything need to be done on lbryum for this or is the issue now only on lbrynet and lbrycrd? Can this issue be closed (in preparation for lbryum being merged into lbry)?
