### ISSUE TITLE
_mktx function under commands needs to be fixed

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbryum#33]
Some hacks here, should be fixed as it is making merge from electrum difficult (_mktx seems to have changed significantly in electrum from when we last forked), and is affecting functionality for regular send functions. 

https://github.com/lbryio/lbryum/blob/master/lib/commands.py#L401
https://github.com/lbryio/lbryum/blob/master/lib/commands.py#L402

We should add in a custom function for making claimtrie transactions and leave _mktx back to its original state before the fork.

**Comment by eukreign** [comment]
@kaykurokawa is this issue still valid? I think electrum and lbryum have diverged to the point where trying to pull stuff from electrum into lbryum would be more hassle than it's worth; especially if the near term goal is to merge lbryum into lbry.
