### ISSUE TITLE
Can't send lbc

### ISSUE THREAD

**Issue by abueide** [lbryio/lbryum#35]
Fails to send lbc via gui with error: invalid line found 1: insert-send-to-address-here
Sending via ./lbryum paytoandsend works

**Comment by kaykurokawa** [comment]
Got the same thing.  A warning with:
-----------------
Invalid Lines found:
Line #1: [Address]
-----------------
where [Address] is a valid lbry address

**Comment by abueide** [comment]
@kaykurokawa maybe its still expecting a btc address somewhere?
