### ISSUE TITLE
Unverified transaction being removed on startup causes a get_addr_balance error

### ISSUE THREAD

**Issue by jackrobison** [lbryio/lbryum#40]
The transaction gets removed here:

https://github.com/lbryio/lbryum/blob/master/lib/wallet.py#L1184

Which then causes an error here:

https://github.com/lbryio/lbryum/blob/master/lib/wallet.py#L625

**Comment by jackrobison** [comment]
This works, but likely isn't ideal:

https://github.com/lbryio/lbryum/pull/41

**Comment by kaykurokawa** [comment]
I see the problem. 
I think , this might cause another bug when doing SPV verification.. 
I'll  add a data storage for claimtrie transactions to the wallet, I think that will be cleaner. 
Later on, I'd really like to move to coding a seperate wallet class for claimtrie transactions but that will take some time.

**Comment by kaykurokawa** [comment]
cl
