### ISSUE TITLE
no catch on queue.get in lbryio/lbryum/blob/master/lib/network.py @ line 830

### ISSUE THREAD

**Issue by pierre1024** [lbryio/lbryum#77]
python doc says :  If timeout is a positive number, it blocks at most timeout seconds and raises the Empty exception if no item was available within that time.
So i think you have to catch exception and return a timeout error.
call is done by broadcast fct in commands.py @ 235 , timeout is 30 seconds i don't know if it's enough for a transaction.
Here a traceback : 

> 
"message": "Traceback (most recent call last):\n  File \"/opt/venvs/lbrynet/local/lib/python2.7/site-packages/twisted/internet/defer.py\", line 434, in errback\n    self._startRunCallbacks(fail)\n  File \"/opt/venvs/lbrynet/local/lib/python2.7/site-packages/twisted/internet/defer.py\", line 501, in _startRunCallbacks\n    self._runCallbacks()\n  File \"/opt/venvs/lbrynet/local/lib/python2.7/site-packages/twisted/internet/defer.py\", line 588, in _runCallbacks\n    current.result = callback(current.result, *args, **kw)\n  File \"/opt/venvs/lbrynet/local/lib/python2.7/site-packages/twisted/internet/defer.py\", line 1184, in gotResult\n    _inlineCallbacks(r, g, deferred)\n--- <exception caught here> ---\n  File \"/opt/venvs/lbrynet/local/lib/python2.7/site-packages/twisted/internet/defer.py\", line 1126, in _inlineCallbacks\n    result = result.throwExceptionIntoGenerator(g)\n  File \"/opt/venvs/lbrynet/local/lib/python2.7/site-packages/twisted/python/failure.py\", line 389, in throwExceptionIntoGenerator\n    return g.throw(self.type, self.value, self.tb)\n  File \"/opt/venvs/lbrynet/local/lib/python2.7/site-packages/lbrynet/lbrynet_daemon/Daemon.py\", line 792, in _publish_stream\n    claim_out = yield publisher.publish_stream(name, file_path, bid, metadata)\n  File \"/opt/venvs/lbrynet/local/lib/python2.7/site-packages/twisted/internet/defer.py\", line 1126, in _inlineCallbacks\n    result = result.throwExceptionIntoGenerator(g)\n  File \"/opt/venvs/lbrynet/local/lib/python2.7/site-packages/twisted/python/failure.py\", line 389, in throwExceptionIntoGenerator\n    return g.throw(self.type, self.value, self.tb)\n  File \"/opt/venvs/lbrynet/local/lib/python2.7/site-packages/lbrynet/lbrynet_daemon/Publisher.py\", line 50, in publish_stream\n    claim_out = yield self.make_claim(name, bid, metadata)\n  File \"/opt/venvs/lbrynet/local/lib/python2.7/site-packages/twisted/internet/defer.py\", line 1126, in _inlineCallbacks\n    result = result.throwExceptionIntoGenerator(g)\n  File \"/opt/venvs/lbrynet/local/lib/python2.7/site-packages/twisted/python/failure.py\", line 389, in throwExceptionIntoGenerator\n    return g.throw(self.type, self.value, self.tb)\n  File \"/opt/venvs/lbrynet/local/lib/python2.7/site-packages/lbrynet/lbrynet_daemon/Publisher.py\", line 65, in make_claim\n    claim_out = yield self.wallet.claim_name(name, bid, validated_metadata)\n  File \"/opt/venvs/lbrynet/local/lib/python2.7/site-packages/twisted/internet/defer.py\", line 1126, in _inlineCallbacks\n    result = result.throwExceptionIntoGenerator(g)\n  File \"/opt/venvs/lbrynet/local/lib/python2.7/site-packages/twisted/python/failure.py\", line 389, in throwExceptionIntoGenerator\n    return g.throw(self.type, self.value, self.tb)\n  File \"/opt/venvs/lbrynet/local/lib/python2.7/site-packages/lbrynet/core/Wallet.py\", line 647, in claim_name\n    claim = yield self._send_name_claim(name, _metadata, bid)\n  File \"/opt/venvs/lbrynet/local/lib/python2.7/site-packages/twisted/python/threadpool.py\", line 246, in inContext\n    result = inContext.theWork()\n  File \"/opt/venvs/lbrynet/local/lib/python2.7/site-packages/twisted/python/threadpool.py\", line 262, in <lambda>\n    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)\n  File \"/opt/venvs/lbrynet/local/lib/python2.7/site-packages/twisted/python/context.py\", line 118, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n  File \"/opt/venvs/lbrynet/local/lib/python2.7/site-packages/twisted/python/context.py\", line 81, in callWithContext\n    return func(*args,**kw)\n  File \"/opt/venvs/lbrynet/local/lib/python2.7/site-packages/lbryum/commands.py\", line 79, in func_wrapper\n    return func(*args, **kwargs)\n  File \"/opt/venvs/lbrynet/local/lib/python2.7/site-packages/lbryum/commands.py\", line 238, in broadcast\n    return self.network.synchronous_get(('blockchain.transaction.broadcast', [str(t)]))\n  File \"/opt/venvs/lbrynet/local/lib/python2.7/site-packages/lbryum/network.py\", line 830, in synchronous_get\n    r = queue.get(True, timeout)\n  File \"/usr/lib/python2.7/Queue.py\", line 176, in get\n    raise Empty\nQueue.Empty: \n"

>

**Comment by jobevers** [comment]
Thanks. Will take a look.

**Comment by kaykurokawa** [comment]
fixed in https://github.com/lbryio/lbryum/pull/82
